// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as Form$ReactHooksTemplate from "./Form.bs.js";
import * as Main$ReactHooksTemplate from "./Main.bs.js";
import * as NotFoundPage$ReactHooksTemplate from "./NotFoundPage.bs.js";

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url.path;
  if (match) {
    switch (match[0]) {
      case "login" :
          if (!match[1]) {
            return React.createElement(Form$ReactHooksTemplate.make, {
                        formType: "login"
                      });
          }
          break;
      case "register" :
          if (!match[1]) {
            return React.createElement(Form$ReactHooksTemplate.make, {
                        formType: "register"
                      });
          }
          break;
      default:
        
    }
  } else {
    return React.createElement(Main$ReactHooksTemplate.make, { });
  }
  return React.createElement(NotFoundPage$ReactHooksTemplate.make, { });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
