// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, "Hello World");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
