// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as Main$ReactHooksTemplate from "./Main.bs.js";
import * as Login$ReactHooksTemplate from "./Login.bs.js";
import * as Register$ReactHooksTemplate from "./Register.bs.js";
import * as NotFoundPage$ReactHooksTemplate from "./NotFoundPage.bs.js";

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "login" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(Login$ReactHooksTemplate.make, { });
          }
          break;
      case "register" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(Register$ReactHooksTemplate.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    return React.createElement(Main$ReactHooksTemplate.make, { });
  }
  if (exit === 1) {
    return React.createElement(NotFoundPage$ReactHooksTemplate.make, { });
  }
  
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
