// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var initialState = /* record */[/* errors : [] */0];

function reducer(state, action) {
  return /* record */[/* errors : :: */[
            /* record */[
              /* field */"username",
              /* message */"Username is required"
            ],
            state[/* errors */0]
          ]];
}

function useValidation(formType) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var validate = function (formData) {
    if (formType === "login") {
      return Curry._1(dispatch, /* UsernameRequired */[formData[/* username */0]]);
    } else {
      return 0;
    }
  };
  return /* tuple */[
          match[0],
          validate
        ];
}

export {
  initialState ,
  reducer ,
  useValidation ,
  
}
/* react Not a pure module */
