// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Form(Props) {
  return React.createElement("div", {
              className: "section is-fullheight"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "column is-4 is-offset-4"
                    }, React.createElement("div", {
                          className: "box"
                        }, React.createElement("form", undefined, React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Email Address"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "email",
                                          required: true,
                                          type: "email"
                                        }))), React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Password"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "password",
                                          required: true,
                                          type: "password"
                                        }))), React.createElement("button", {
                                  className: "button is-block is-info is-fullwidth",
                                  type: "submit"
                                }, "Login"))))));
}

var make = Form;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
