// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Form$ReactHooksTemplate from "./Form.bs.js";

function str(prim) {
  return prim;
}

function Login(Props) {
  var logger = function (param) {
    console.log("Form submitted");
    return /* () */0;
  };
  var match = Form$ReactHooksTemplate.useForm(logger);
  var handleChange = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "section is-fullheight"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "column is-4 is-offset-4"
                    }, React.createElement("div", {
                          className: "box"
                        }, React.createElement("form", {
                              onSubmit: match[2]
                            }, React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Username"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "username",
                                          required: true,
                                          type: "text",
                                          value: state[/* username */2],
                                          onChange: handleChange
                                        }))), React.createElement("div", {
                                  className: "field"
                                }, React.createElement("label", {
                                      className: "label"
                                    }, "Password"), React.createElement("div", {
                                      className: "control"
                                    }, React.createElement("input", {
                                          className: "input",
                                          name: "password",
                                          required: true,
                                          type: "password",
                                          value: state[/* password */1],
                                          onChange: handleChange
                                        }))), React.createElement("button", {
                                  className: "button is-block is-info is-fullwidth",
                                  type: "submit"
                                }, "Login"))))));
}

var make = Login;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
