// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Main(Props) {
  return React.createElement("div", {
              className: "section is-fullheight"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "column is-4 is-offset-4"
                    }, React.createElement("h1", {
                          className: "is-size-1"
                        }, "Main Page"), React.createElement("hr", undefined), React.createElement("a", {
                          className: "is-size-4",
                          href: "/login"
                        }, "Login"), React.createElement("p", {
                          className: "is-size-5"
                        }, "or"), React.createElement("a", {
                          className: "is-size-4",
                          href: "/register"
                        }, "Register"))));
}

var make = Main;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
