// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var initialFormData = {
  username: "",
  email: "",
  password: ""
};

var registerFormRules = [
  {
    id: 0,
    field: "username",
    message: "Username must have at least 5 characters.",
    valid: false
  },
  {
    id: 1,
    field: "email",
    message: "Email must have at least 5 characters.",
    valid: false
  },
  {
    id: 2,
    field: "email",
    message: "Email must be a valid email address.",
    valid: false
  },
  {
    id: 3,
    field: "password",
    message: "Password must have at least 10 characters.",
    valid: false
  }
];

var loginFormRules = [
  {
    id: 0,
    field: "email",
    message: "Email is required.",
    valid: false
  },
  {
    id: 1,
    field: "email",
    message: "Email must be a valid email address.",
    valid: false
  },
  {
    id: 2,
    field: "password",
    message: "Password is required.",
    valid: false
  }
];

function validEmail(email) {
  var re = /^(([^<>()\[\]\.,;:\s@']+(\.[^<>()\[\]\.,;:\s@']+)*)|('.+'))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  return re.test(email);
}

function areAllRulesValid(formRules) {
  return Belt_Array.every(formRules, (function (rule) {
                return rule.valid;
              }));
}

function setRuleToValid(rules, id) {
  return $$Array.map((function (rule) {
                if (rule.id === id) {
                  return {
                          id: rule.id,
                          field: rule.field,
                          message: rule.message,
                          valid: true
                        };
                } else {
                  return rule;
                }
              }), rules);
}

function setRuleToInvalid(rules, id) {
  return $$Array.map((function (rule) {
                if (rule.id === id) {
                  return {
                          id: rule.id,
                          field: rule.field,
                          message: rule.message,
                          valid: false
                        };
                } else {
                  return rule;
                }
              }), rules);
}

function registerFormRulesReducer(state, action) {
  switch (action.TAG | 0) {
    case /* UsernameLongEnough */0 :
        if (action._0.length >= 5) {
          return setRuleToValid(state, 0);
        } else {
          return setRuleToInvalid(state, 0);
        }
    case /* EmailLongEnough */1 :
        if (action._0.length >= 5) {
          return setRuleToValid(state, 1);
        } else {
          return setRuleToInvalid(state, 1);
        }
    case /* EmailForRegistrationValid */2 :
        if (validEmail(action._0)) {
          return setRuleToValid(state, 2);
        } else {
          return setRuleToInvalid(state, 2);
        }
    case /* PasswordLongEnough */3 :
        if (action._0.length >= 10) {
          return setRuleToValid(state, 3);
        } else {
          return setRuleToInvalid(state, 3);
        }
    
  }
}

function loginFormRulesReducer(state, action) {
  switch (action.TAG | 0) {
    case /* EmailRequired */0 :
        if (action._0.length !== 0) {
          return setRuleToValid(state, 0);
        } else {
          return setRuleToInvalid(state, 0);
        }
    case /* EmailForLoginValid */1 :
        if (validEmail(action._0)) {
          return setRuleToValid(state, 1);
        } else {
          return setRuleToInvalid(state, 1);
        }
    case /* PasswordRequired */2 :
        if (action._0.length !== 0) {
          return setRuleToValid(state, 2);
        } else {
          return setRuleToInvalid(state, 2);
        }
    
  }
}

function formReducer(state, action) {
  if (typeof action === "number") {
    return initialFormData;
  }
  switch (action.TAG | 0) {
    case /* SetUsername */0 :
        return {
                username: action._0,
                email: state.email,
                password: state.password
              };
    case /* SetEmail */1 :
        return {
                username: state.username,
                email: action._0,
                password: state.password
              };
    case /* SetPassword */2 :
        return {
                username: state.username,
                email: state.email,
                password: action._0
              };
    
  }
}

function useForm(formType, callback) {
  var match = React.useState(function () {
        return false;
      });
  var setAllValid = match[1];
  var allValid = match[0];
  var match$1 = React.useReducer(formReducer, initialFormData);
  var dispatchFormData = match$1[1];
  var formData = match$1[0];
  var match$2 = React.useReducer(registerFormRulesReducer, registerFormRules);
  var dispatchRegisterFormRules = match$2[1];
  var match$3 = React.useReducer(loginFormRulesReducer, loginFormRules);
  var dispatchLoginFormRules = match$3[1];
  var formRules;
  switch (formType) {
    case "login" :
        formRules = match$3[0];
        break;
    case "register" :
        formRules = match$2[0];
        break;
    default:
      formRules = [];
  }
  var validate = function (formDataOpt, param) {
    var formData$1 = formDataOpt !== undefined ? formDataOpt : formData;
    switch (formType) {
      case "login" :
          Curry._1(dispatchLoginFormRules, {
                TAG: 0,
                _0: formData$1.email,
                [Symbol.for("name")]: "EmailRequired"
              });
          Curry._1(dispatchLoginFormRules, {
                TAG: 1,
                _0: formData$1.email,
                [Symbol.for("name")]: "EmailForLoginValid"
              });
          return Curry._1(dispatchLoginFormRules, {
                      TAG: 2,
                      _0: formData$1.password,
                      [Symbol.for("name")]: "PasswordRequired"
                    });
      case "register" :
          Curry._1(dispatchRegisterFormRules, {
                TAG: 0,
                _0: formData$1.username,
                [Symbol.for("name")]: "UsernameLongEnough"
              });
          Curry._1(dispatchRegisterFormRules, {
                TAG: 1,
                _0: formData$1.email,
                [Symbol.for("name")]: "EmailLongEnough"
              });
          Curry._1(dispatchRegisterFormRules, {
                TAG: 2,
                _0: formData$1.email,
                [Symbol.for("name")]: "EmailForRegistrationValid"
              });
          return Curry._1(dispatchRegisterFormRules, {
                      TAG: 3,
                      _0: formData$1.password,
                      [Symbol.for("name")]: "PasswordLongEnough"
                    });
      default:
        return ;
    }
  };
  var handleChange = function (evt) {
    evt.persist();
    var match = evt.target.name;
    switch (match) {
      case "email" :
          return Curry._1(dispatchFormData, {
                      TAG: 1,
                      _0: evt.target.value,
                      [Symbol.for("name")]: "SetEmail"
                    });
      case "password" :
          return Curry._1(dispatchFormData, {
                      TAG: 2,
                      _0: evt.target.value,
                      [Symbol.for("name")]: "SetPassword"
                    });
      case "username" :
          return Curry._1(dispatchFormData, {
                      TAG: 0,
                      _0: evt.target.value,
                      [Symbol.for("name")]: "SetUsername"
                    });
      default:
        return ;
    }
  };
  var handleSubmit = function (evt) {
    evt.preventDefault();
    return Curry._1(setAllValid, (function (param) {
                  return Belt_Array.every(formRules, (function (rule) {
                                return rule.valid;
                              }));
                }));
  };
  React.useEffect((function () {
          validate(formData, undefined);
          
        }), [formData]);
  React.useEffect((function () {
          if (allValid) {
            Curry._1(callback, undefined);
            Curry._1(dispatchFormData, /* ResetState */0);
            return ;
          }
          
        }), [allValid]);
  return [
          formData,
          formRules,
          handleChange,
          handleSubmit
        ];
}

export {
  initialFormData ,
  registerFormRules ,
  loginFormRules ,
  validEmail ,
  areAllRulesValid ,
  setRuleToValid ,
  setRuleToInvalid ,
  registerFormRulesReducer ,
  loginFormRulesReducer ,
  formReducer ,
  useForm ,
  
}
/* react Not a pure module */
